### ISSUE TITLE
Default Doesn't Seem to Work

### ISSUE THREAD

**Issue by abmagil** [suchipi/match-discriminated-union#1]
https://codesandbox.io/p/sandbox/testing-match-disciminated-union-wxvks8?file=%2Fsrc%2FApp.tsx%3A3%2C20

I can't seem to get the default case handler to work. I've copied the examples from the README into the above sandbox and also tried to build my own examples. Both fail to execute the default handler.

Looking into https://github.com/suchipi/match-discriminated-union/blob/main/src/index.ts, I don't see any code that _would_ cause the default handler to run, either.

**Comment by suchipi** [comment]
Yikes, that's embarrassing. Thanks for letting me know; fixed in https://github.com/suchipi/match-discriminated-union/commit/3c6f4f2668f4486355a7b23de09573d31a8b79ed (which was published as version 1.0.1 on npm).

**Comment by abmagil** [comment]
Amazing! Thank you for such a speedy resolution!
